### ISSUE TITLE
HACS compatible

### ISSUE THREAD

**Issue by gitdeath** [Djelibeybi/ha-lifx-beta#10]
This integration doesn't appear in HACS "Add repository" search accessed by using the "+Explore & Download Repositories" button. 

HA version: 2022.5.5
HACS version: 1.25.0

**Comment by Djelibeybi** [comment]
Correct. I haven't submitted it to the main HAC list of repos. You need to add it manually as a custom repo.

**Comment by gitdeath** [comment]
My bad I misunderstood your post in the lifx threads as saying HACS was the way to install it. Closing this.
