### ISSUE TITLE
One bulb not staying available

### ISSUE THREAD

**Issue by gregg098** [Djelibeybi/ha-lifx-beta#15]
Currently on 2022.06.06 of this integration.
I have 3 LIFX bulbs.  Two color bulbs (LIFX A19) and one white bulb (White 800). With the stock Home Assistant integration, I originally had issues with all bulbs as of the last version or so of Home Assistant. With the current beta version of this integration, I only have issues with the white bulb. No matter what I do, it goes unavailable after a bit of time after a power cycle.

I see these messages for each of my bulbs, but the White one I see it multiple times (some information scrubbed):

`2022-06-11 07:43:11 DEBUG (MainThread) [custom_components.lifx.light] First discovery response received from 192.168.xx.xx (mac)`

Later I see this for the White bulb:
`2022-06-11 07:43:12 DEBUG (MainThread) [custom_components.lifx.light] Failed to discover product information for 192.168.xx.xx (mac)`

It repeates over and over in my logs. Bulb and Home Assistant are on the same subnet, so it isnt a discovery or firewall issue. Everything was working until the last version of Home Assistant I believe.

Power cycling brings it back, then it drops off again some time later.

Ill do some tests later and post more logs (before, during, after power cycle).

**Comment by gregg098** [comment]
After a power cycle:

```
2022-06-11 09:04:42 DEBUG (MainThread) [custom_components.lifx.light] First discovery response received from 192.168.xx.xx (mac)

2022-06-11 09:04:42 DEBUG (MainThread) [custom_components.lifx.light] Entity created for Master Bedroom End Table (mac)

2022-06-11 09:06:47 DEBUG (MainThread) [custom_components.lifx.light] Disconnected from Master Bedroom End Table (mac)

2022-06-11 09:06:47 DEBUG (MainThread) [custom_components.lifx.light] Disconnected from Master Bedroom End Table (mac)

2022-06-11 09:06:57 DEBUG (MainThread) [custom_components.lifx.light] Reconnected to Master Bedroom End Table (mac)
```

At this point its no longer available.

**Comment by Djelibeybi** [comment]
Can you please give me the exact bulb type and the firmware version it's running?

**Comment by gregg098** [comment]
LIFX White 800 (LV)
Firmware: 1.22

**Comment by gregg098** [comment]
I completely removed LIFX (with the beta still installed). Restarted Home Assistant. Rigth away it discovered the 2 color bulbs. I power cycled the white bulb and it was found right away. Been 15ish minutes, so far so good. Usually drops off by now.

**Comment by Djelibeybi** [comment]
Ah, ok. I don't have any original (gen1) bulbs left. I'll create a test version for you to try tomorrow to see if we can narrow down why it's failing.

**Comment by gregg098** [comment]
So far so good. Don't know why I had to remove the integration and reinstall it, but my light is still available after 8 or so hours. Nothing of interest in the logs outside of what I already showed.  Think we can close this unless there's anything else that might help?

**Comment by Djelibeybi** [comment]
If it's working, it's working. :) Issue closed. If anything else crops up, please open a  new issue.

**Comment by gregg098** [comment]
I spoke too soon. This one bulb decided to become unavailable again last night. My logs don't show anything except the Reconnected and Disconnected messages I posted in a previous post.  The bulb is available in the LIFX app, just not HA.

I may have mentioned it already, but HA is on the same VLAN as the bulbs, so there are no mDNS/firewall rules or repeaters in the mix.  Other bulbs still working just fine.

**Comment by Djelibeybi** [comment]
Bulbs becoming unavailable isn't unexpected. But they should eventually be rediscovered by the integration and become available again.
