### ISSUE TITLE
Bulb going unavailable

### ISSUE THREAD

**Issue by kryanth** [Djelibeybi/ha-lifx-beta#18]
I'm seeing 

DEBUG (MainThread) [custom_components.lifx.light] Disconnected from Entrance Light 02 (MAC)

from a couple downlights (LIFX DL Colour 700lm) - firmware 2.80
Wifi strength : 3/5 

They are on a dedicated vlan, using the specific broadcast configuration to loop them in. I dont have them connected to the LIFX cloud, however I can connect to that VLAN with my phone and the light responds instantly.

If I reload the integration, the light is picked up immediately for another few hours. 

There are maybe 3-4 lights that consistently display this behaviour. According to my UNIFI integration, the light stays online. 

There are 21 downlights in total, all are hardwired effectively and can't be turned off (except at the breaker). There are multiple AP's with no connectivity issues.

It does not appear to be reconnecting until the integration is reloaded - certainly it goes hours. 

Running latest 2022.07.01

A periodic service that lets me schedule a rescan / reconnect - I can see when they go unavailable, and afaict they are definitely not unavailable - I'm just gonna automate that, I'm not too far off just automating an integration reload at the moment.

**Comment by Djelibeybi** [comment]
Remove the beta and use the new LIFX integration in 2022.8. It has way better connection control and far more detailed debug logging too. 

I will update the docs on this repo to make it clear it has been superseded by upstream changes.

**Comment by Djelibeybi** [comment]
Having said that, the hardcoding of addresses in this beta prevents it from doing rediscovery/reconnect, something that we've already fixed upstream.

**Comment by Djelibeybi** [comment]
This should no longer be an issue with the latest `2022.11` release in Home Assistant. If it is, please open an issue in the Core repo: https://github.com/home-assistant/core
