### ISSUE TITLE
Remove Integration

### ISSUE THREAD

**Issue by seanmccabe** [Djelibeybi/ha-lifx-beta#19]
Is there any-way to remove this integration without removing the whole Lifx integration and losing device names, areas etc. that are all setup?

**Comment by Djelibeybi** [comment]
Yeah, just remove it with HACS. It'll ask if you want to ignore the configuration: just say yes.

**Comment by Djelibeybi** [comment]
If you installed it manually, just delete the `lifx` folder from `custom_components`.

**Comment by seanmccabe** [comment]
> Yeah, just remove it with HACS. It'll ask if you want to ignore the configuration: just say yes.

Duh, didn't even see the "ignore" on the left, my mind just saw it as cancel I think. Appreciated.

**Comment by Djelibeybi** [comment]
> Duh, didn't even see the "ignore" on the left, my mind just saw it as cancel I think. 

Yep, me too until I had to remove this very beta myself a while ago. 😂

**Comment by seanmccabe** [comment]
Just let me know if you ever chuck stuff into this that you want tested, happy to load it in again :)

**Comment by seanmccabe** [comment]
Removed it now all my lights are unavailable :(

**Comment by Djelibeybi** [comment]
It'll take a while for the migrate to complete. It tries a _lot_ of different discovery mechanisms now. Just give it time. It migrates in batches so the more lights you have, the longer it'll take. And it only checks every 15 minutes.
