### ISSUE TITLE
LIFX Lights go unavailable during light up dim automation or otherwise sporadically after commands are issued to them.

### ISSUE THREAD

**Issue by x3style** [Djelibeybi/ha-lifx-beta#36]
2023-01-08 00:01:57.504 ERROR (MainThread) [custom_components.lifx] Error fetching Stairs 1 (10.0.53.3) data: Failed to update Stairs 1: No response from Stairs 1 (10.0.53.3) [d0:73:d5:2e:46:47]

What version of Home Assistant Core has the issue?
Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

What was the last working version of Home Assistant Core?
Don't remember I update regularly as new versions come out. However I didn't use to have this problem a while back.

What type of installation are you running?
Version | core-2023.1.1
Installation Type | Home Assistant OS

Integration causing the issue
LIFX Official
https://www.home-assistant.io/integrations/lifx/
LIFX Beta as well.
https://github.com/Djelibeybi/ha-lifx-beta

[config_entry-lifx-258a5b54153c3faaa013d311f9652537.json.txt](https://github.com/Djelibeybi/ha-lifx-beta/files/10367427/config_entry-lifx-258a5b54153c3faaa013d311f9652537.json.txt)

Log File relevant message:
2023-01-08 00:01:57.504 ERROR (MainThread) [custom_components.lifx] Error fetching Stairs 1 (10.0.53.3) data: Failed to update Stairs 1: No response from Stairs 1 (10.0.53.3) [d0:73:d5:2e:46:47]

**Comment by Djelibeybi** [comment]
Could you please download the diagnostics from the "Stairs 1" device and upload that? The one above is for your "Entrance Light 1".

Something you might want to try, given this is a LIFX Z, is testing different orientations of the control/radio box between the strip and the power adapter. The WiFi module is inside that box and it has a very annoying antenna pattern. Reorienting it towards your WiFi adapter and switching it from vertical to horizontal (or vice-versa) can have a significant impact in stability and reducing latency.

**Comment by x3style** [comment]
[config_entry-lifx-b1f4786a36b82ec5ce3d8e5fe456bfc5.json.txt](https://github.com/Djelibeybi/ha-lifx-beta/files/10367454/config_entry-lifx-b1f4786a36b82ec5ce3d8e5fe456bfc5.json.txt)
[config_entry-lifx-bb8c0b55edc882c113a89c3d4721ac3a.json.txt](https://github.com/Djelibeybi/ha-lifx-beta/files/10367455/config_entry-lifx-bb8c0b55edc882c113a89c3d4721ac3a.json.txt)

**Comment by x3style** [comment]
> Could you please download the diagnostics from the "Stairs 1" device and upload that? The one above is for your "Entrance Light 1".
> 
> Something you might want to try, given this is a LIFX Z, is testing different orientations of the control/radio box between the strip and the power adapter. The WiFi module is inside that box and it has a very annoying antenna pattern. Reorienting it towards your WiFi adapter and switching it from vertical to horizontal (or vice-versa) can have a significant impact in stability and reducing latency.

The hardware is fixed / embedded and cannot be moved on any of my Strips.

**Comment by Djelibeybi** [comment]
Ah, that's a pity. It may be useful to enable the RSSI sensor entity to see what sort of signal the strips are getting. That would at least tell us if this is a connectivity/latency-related issue.

**Comment by x3style** [comment]
As said they work fine via the LIFX app. If there was a hardware issue LIFX App would have the same problems.

**Comment by x3style** [comment]
![image](https://user-images.githubusercontent.com/84071923/211175289-bf9be43b-1da1-48cf-9214-36ec3120c64d.png)
![image](https://user-images.githubusercontent.com/84071923/211175294-b908e794-579f-4034-b1e6-e6cb12277ec4.png)

**Comment by Djelibeybi** [comment]
You'd think that, but it's not strictly speaking true: the LIFX app cheats and uses the cloud connection if it can't find the bulb on the local network. As that connection is managed by the bulb and we have no visibility into it's stability, it could be flapping as often as the Home Assistant one does. 

And UniFi's wifi experience is utterly meaningless in this context as it doesn't (appear to) measure any useful IoT/LIFX related values.

**Comment by Djelibeybi** [comment]
Seeing

**Comment by Djelibeybi** [comment]
The RSSI value reported by my Beam is currently -76dBm while UniFi puts it at -40dBm. I need the value from the Z strip, not UniFi.

**Comment by x3style** [comment]
I apologies mate, I merely wanted to report that I have similar issues like others before reported, I don't really have the time to debug this.

**Comment by Djelibeybi** [comment]
Fair enough, thanks for your help so far. I'll close this issue as I have grabbed the diagnostics.
