### ISSUE TITLE
Latest beta throws time out warnings

### ISSUE THREAD

**Issue by mark007** [Djelibeybi/ha-lifx-beta#49]
With the latest beta from today it's throwing hundreds of these warnings per hour. The Mac seems to be all zeroes so maybe it's indicating an issue with either the integration or at least with the log message.

```
Logger: custom_components.lifx
Source: custom_components/lifx/coordinator.py:184
Integration: LIFX ([documentation](https://github.com/Djelibeybi/ha-lifx-beta))
First occurred: 22:59:01 (482 occurrences)
Last logged: 23:41:36

Time out updating 192.168.8.45 (00:00:00:00:00:00). Reconnecting.
Time out updating 192.168.8.42 (00:00:00:00:00:00). Reconnecting.
Time out updating 192.168.8.43 (00:00:00:00:00:00). Reconnecting.
Time out updating 192.168.8.39 (00:00:00:00:00:00). Reconnecting.
Time out updating 192.168.8.41 (00:00:00:00:00:00). Reconnecting.
```

**Comment by Djelibeybi** [comment]
That is really disappointing, because I'm getting zero warnings and was hoping things were finally looking up.

**Comment by mark007** [comment]
Thanks so much

**Comment by Djelibeybi** [comment]
Now, `2032.2.1b2` will still throw actual `ERRORS` if the device doesn't respond after the reconnect, so let me know if that happens and if it's at the same level, less or more than before. For my fleet of 60+, this release is remarkably stable.
