### ISSUE TITLE
Z Strips Becoming Unrespnsive

### ISSUE THREAD

**Issue by narc792** [Djelibeybi/ha-lifx-beta#6]
Using the beta here to try and mitigate connection issues. I have two Z Strips that are still losing connection with Home Assistant. They are always available in the LIFX App. 

Prior to the beta I would restart my router and they’d reappear. After installing the beta they lose connection less frequently but when they do I need to delete the LIFX integration, restart my router, then restart Home Assistant to get them to appear again. Any thoughts on how to fix this? The two Z Strips are the only LIFX devices I have.

**Comment by Djelibeybi** [comment]
Yeah, there is a bug in the beta that means it sometimes won't reconnect at all. Try hitting the Reload option on the Integrations page, that should kick things in the right spot.

**Comment by robchandhok** [comment]
Ah.  This makes sense, I just had the same behavior (could see the responses in the DEBUG log entries from the Z strip, but never because "available" in HA). 

If there is something I can do to help debug, let me know!

**Comment by Djelibeybi** [comment]
As I mentioned in another issue, the plan is to deprecate/remove this beta once the switch bypass logic has been merged upstream and released in a non-beta version: https://github.com/home-assistant/core/pull/67726

If you don't have any LIFX Switches, I recommend removing this LIFX Beta to see if the core integration works for you now. They have made a few improvements upstream that has had an impact on stability (at least for me).

**Comment by robchandhok** [comment]
Thanks very much - I see your point.  Will the core implementation allow for adjusting the settings/timeouts?  That turns out to be critical.  I will try the core implementation (I'm on the very latest and beta usually) in a few days.  Really appreciate your response and work on this.

**Comment by Djelibeybi** [comment]
They currently don't, but I also don't think my beta exposes them effectively either. If more folks test the updated core integration, that would allow for more core-specific modifications in future.

**Comment by narc792** [comment]
> As I mentioned in another issue, the plan is to deprecate/remove this beta once the switch bypass logic has been merged upstream and released in a non-beta version: [home-assistant/core#67726](https://github.com/home-assistant/core/pull/67726)
> 
> If you don't have any LIFX Switches, I recommend removing this LIFX Beta to see if the core integration works for you now. They have made a few improvements upstream that has had an impact on stability (at least for me).

The core integration is much worse for me still than the beta for my Z Strips. I can barely get a day without the strips becoming unavailable on the latest core release.

**Comment by Djelibeybi** [comment]
Do you have multiple NICs active on your Home Assistant server? If so, you may want to set a specific NIC instead of relying on the default automatic selection. If you're using wifi: connect a LAN cable to see if that helps.

**Comment by narc792** [comment]
Single NIC on a home assistant blue. Connected via Ethernet. I don’t have any LIFX devices in my other home that runs a Pi4 to test on that right now either.

**Comment by Djelibeybi** [comment]
Huh. I have no idea what's causing your problem, to be honest. There should be very little different between this addon and the official one and I can't think of anything that would cause that problem.

**Comment by Djelibeybi** [comment]
I don't believe it does, but the way this addon does it doesn't work that well either, I've discovered.

**Comment by Djelibeybi** [comment]
This should be resolved by https://github.com/home-assistant/core/pull/70458 when it is merged to the core.
