### ISSUE TITLE
LIFX Switch Buttons not available on some switches

### ISSUE THREAD

**Issue by lox** [Djelibeybi/ha-lifx-beta#63]
I'm on 2023.4.4. I have about 8 LIFX Switches connected to HA via Homekit Controller. My switches control a mix of Lifx bulbs and normal relays. 

I have automations setup to respond to button presses, e.g. `"single press" button1` and toggle my lights or lightgroups. For most, this works great, but I have two different switches that aren't exposing their button events, only the terminal events. 

This is what a working one looks like:
<img width="1166" alt="image" src="https://github.com/Djelibeybi/ha-lifx-beta/assets/15758/cc1e3836-2bcf-40e9-b003-b1694b8b8e7b">

This is one that isn't working:
<img width="1202" alt="image" src="https://github.com/Djelibeybi/ha-lifx-beta/assets/15758/68c6eb45-d8db-4f54-b394-f913f87a8fed">

I've tried removing the switches and re-pairing them to Homekit Controller, but the events aren't there. 

This is how the working switch is configured in the LIFX app:

```
Wiring Setup:
  Terminal 1:
    Is this terminal wired? Yes
    What is it wired to? LIFX Light
  Terminal 2:
    Is this terminal wired? Yes
    What is it wired to? LIFX Light  
Buttons:
  All empty
```

This is how the non-working switch is configured:

```
Wiring Setup:
  Terminal 1:
    Is this terminal wired? Yes
    What is it wired to? LIFX Light
  Terminal 2:
    Is this terminal wired? No
  Terminal 3:
    Is this terminal wired? No
  Terminal 4:
    Is this terminal wired? No
Buttons:
  All empty
```

Any ideas or info I can provide?

**Comment by lox** [comment]
Oh apologies, I think I have just realized that the switch integration happens outside this integration!

**Comment by ironcrafter54** [comment]
yes It is an issue with homekit controller.
