### ISSUE TITLE
Lights unavailable in HASS, but available on LIFX

### ISSUE THREAD

**Issue by mekenthompson** [Djelibeybi/ha-lifx-beta#8]
I often get lights marked unavailable, subsequently not actionable for my adaptive lighting or automations. When this happens, the lights are still available via LIFX app and I can ping the lights no worries from HASS.

Wondering if there is a need to mark the light as unavailable from HASS? Or why it marks them unavailable? I'll extend that setting in the config and see what happens.

**Comment by Djelibeybi** [comment]
You're not th eonly person to report this and I'm seeing it as well. When this happens, could you please reload the integration from the HASS UI (click the dots and then Reload) to see if that brings the lights back into existence? I probably need to rebase this beta off the newer version of the integration from Core, as they've made some changes there.

**Comment by mekenthompson** [comment]
Yeah - they will usually come back when I reload the integration. I've increased the grace period for marking unavailable to 30 mins. Do you think that will help?

**Comment by Djelibeybi** [comment]
It might. I haven't had enough spare time to work out why they're not coming back automatically during the next discovery cycle.

**Comment by mark007** [comment]
Do you guys know if there's any particular timeout or tweaks that can help with this one. Also seeing bulbs stay unavailable while available in lifx app. Restart also solves it.

**Comment by mekenthompson** [comment]
@mark007 I've not found any settings yet that resolve it. I'd assume "Message reply timeout" and "Grace period before marked unavailable" would have helped, but can't find an consistency in this resolving the issue when increasing these.

**Comment by Djelibeybi** [comment]
My recommendation is to switch back to the core integration, especially after https://github.com/home-assistant/core/pull/67721 is merged.

**Comment by mekenthompson** [comment]
@Djelibeybi @mark007  I've just removed the beta via HACS and tested native LIFX integration, almost all my lights show as unavailable now. Something upstream seems to have made the issue worse than better. 

If you use native integration does it resolve lifx light availablity or make it worse for you?

**Comment by Djelibeybi** [comment]
yeah, I still haven't had the switch fix merged upstream. Maybe I'll try get that in as a single update.

**Comment by Djelibeybi** [comment]
I've opened https://github.com/home-assistant/core/pull/67726 which skips LIFX Switches in the core integration.

**Comment by Djelibeybi** [comment]
I've just submitted https://github.com/home-assistant/core/pull/70458 which significantly improves the reliability and performance of LIFX bulb detection, so I'm closing this issue (and archiving this repo) in favour of improving the core integration directly.
